Repository nsqio/nsq, pull requests merged in 2018-07, with the labels that each got.

#1047 nsqd: make statsd SpreadWriter use exit chan
  internal/writers/spread_writer.go
  nsqd/nsqd.go
  nsqd/statsd.go
Labels: chore

#1050 nsqd: create Topic paused
  nsqd/nsqd.go
  nsqd/topic.go
Labels: chore

#1053 nsqd: start Topic messagePump separately from create
  nsqadmin/nsqadmin.go
  nsqd/nsqd.go
  nsqd/topic.go
Labels: chore

#1058 release prep
  ChangeLog.md
  internal/version/binary.go
Labels: docs

#753 nsqadmin: missing channel from topic list
  internal/clusterinfo/types.go
  nsqadmin/bindata.go
  nsqadmin/static/js/views/topic.hbs
Labels: bug

#1066 nsqd: deflake TestReconfigure
  nsqd/nsqd.go
  nsqd/nsqd_test.go
Labels: test
