Repository nsqio/nsq, pull requests merged in 2018-09, with the labels that each got.

#1072 nsq_to_http: add custom header flag
  apps/nsq_to_http/http.go
  apps/nsq_to_http/nsq_to_http.go
  apps/nsq_to_http/nsq_to_http_test.go
Labels: feature

#856 nsqadmin: base path
  apps/nsqadmin/main.go
  nsqadmin/bindata.go
  nsqadmin/http.go
  nsqadmin/nsqadmin.go
  nsqadmin/options.go
  nsqadmin/static/html/index.html
  nsqadmin/static/js/app_state.js
  nsqadmin/static/js/collections/nodes.js
  nsqadmin/static/js/collections/topics.js
  nsqadmin/static/js/lib/handlebars_helpers.js
  nsqadmin/static/js/models/channel.js
  nsqadmin/static/js/models/node.js
  nsqadmin/static/js/models/topic.js
  nsqadmin/static/js/router.js
  nsqadmin/static/js/views/base.js
  nsqadmin/static/js/views/channel.hbs
  nsqadmin/static/js/views/channel.js
  nsqadmin/static/js/views/counter.js
  nsqadmin/static/js/views/header.hbs
  nsqadmin/static/js/views/lookup.hbs
  nsqadmin/static/js/views/lookup.js
  nsqadmin/static/js/views/node.hbs
  nsqadmin/static/js/views/nodes.hbs
  nsqadmin/static/js/views/topic.hbs
  nsqadmin/static/js/views/topic.js
  nsqadmin/static/js/views/topics.hbs
Labels: feature, request

#1080 nsqadmin: eslint fixes
  nsqadmin/bindata.go
  nsqadmin/static/js/app_state.js
  nsqadmin/static/js/lib/handlebars_helpers.js
  nsqadmin/static/js/main.js
  nsqadmin/static/js/views/app.js
  nsqadmin/static/js/views/base.js
  nsqadmin/static/js/views/channel.js
  nsqadmin/static/js/views/lookup.js
  nsqadmin/static/js/views/topic.js
Labels: chore
