Repository nsqio/nsq, pull requests merged in 2018-08, with the labels that each got.

#1071 nsq_to_file: new flag -rotate-check-interval
  apps/nsq_to_file/file_logger.go
  apps/nsq_to_file/nsq_to_file.go
Labels: feature

#1055 nsqd: remove support for old metadata filename
  nsqd/nsqd.go
  nsqd/nsqd_test.go
Labels: 1.0, chore

#881 nsqd: add producer client connections to /stats
  nsqd/client_v2.go
  nsqd/http.go
  nsqd/nsqd.go
  nsqd/protocol_v2.go
  nsqd/stats.go
Labels: feature

#1075 README: Add Gitee.com logo
  README.md
Labels: docs
