Repository nsqio/nsq, pull requests merged in 2019-01, with the labels that each got.

#1110 nsq_to_file: support for separate working dir for in-progress files
  apps/nsq_to_file/file_logger.go
  apps/nsq_to_file/nsq_to_file.go
Labels: feature

#1116 nsqlookupd: fix orphaned ephemeral topics in registration DB
  nsqlookupd/lookup_protocol_v1.go
Labels: bug

#1117 nsq_to_file: cleanup
  apps/nsq_to_file/consumer_file_logger.go
  apps/nsq_to_file/file_logger.go
  apps/nsq_to_file/nsq_to_file.go
  apps/nsq_to_file/options.go
  apps/nsq_to_file/topic_discoverer.go
Labels: chore

#1119 nsqd: send client TLS cert common_name on authd requests
  internal/auth/authorizations.go
  nsqd/client_v2.go
  nsqd/protocol_v2.go
  nsqd/protocol_v2_test.go
Labels: feature

#1120 nsq_to_file: revert gzip behavior change
  apps/nsq_to_file/file_logger.go
Labels: chore

#1123 nsq_to_file: check for rotate size specifically in rev-incr loop
  apps/nsq_to_file/file_logger.go
Labels: bug

#1125 nsqd: add support for customise output-buffer-timeout
  apps/nsqd/nsqd.go
  nsqd/client_v2.go
  nsqd/options.go
Labels: feature

#1127 nsqd: instrument aggregate message bytes on topics
  nsqd/stats.go
  nsqd/statsd.go
  nsqd/topic.go
Labels: feature

#1129 readme: add SmartServing logo
  README.md
Labels: docs

#1132 internal/http_api: fixed error messages quoting
  internal/http_api/api_response.go
Labels: bug
