Repository nsqio/nsq, pull requests merged in 2020-11, with the labels that each got.

#1292 nsqd: add pool to minimize buffer allocation on message send
  nsqd/buffer_pool.go
  nsqd/channel.go
  nsqd/message.go
  nsqd/protocol_v2.go
  nsqd/topic.go
Labels: perf

#1297 nsqd: seperate broadcast ports for tcp and http
  apps/nsqd/options.go
  nsqd/lookup.go
  nsqd/nsqd.go
  nsqd/options.go
Labels: feature

#1307 *: remove *Context
  nsqadmin/context.go
  nsqadmin/http.go
  nsqadmin/notify.go
  nsqadmin/nsqadmin.go
  nsqd/channel.go
  nsqd/channel_test.go
  nsqd/client_v2.go
  nsqd/context.go
  nsqd/http.go
  nsqd/nsqd.go
  nsqd/nsqd_test.go
  nsqd/protocol_v2.go
  nsqd/protocol_v2_test.go
  nsqd/tcp.go
  nsqd/topic.go
  nsqlookupd/context.go
  nsqlookupd/http.go
  nsqlookupd/lookup_protocol_v1.go
  nsqlookupd/lookup_protocol_v1_test.go
  nsqlookupd/nsqlookupd.go
  nsqlookupd/tcp.go
Labels: chore
