Repository nsqio/nsq, pull requests merged in 2021-08, with the labels that each got.

#1355 *: build multi-arch docker images linux/amd64,linux/arm64
  dist.sh
Labels: feature

#1361 apps/nsqd: initialize nsqd in Init(); move signal handling to go-svc
  apps/nsqd/main.go
  go.mod
  go.sum
Labels: bug

#1364 *: arm64 builds
  dist.sh
Labels: chore

#1348 nsqadmin: update frontend stack
  nsqadmin/gulpfile.js
  nsqadmin/package-lock.json
  nsqadmin/package.json
Labels: chore

#1347 nsqadmin: use go:embed; match graphite key valid charset
  .gitignore
  go.mod
  nsqadmin/README.md
  nsqadmin/bindata.go
  nsqadmin/http.go
  nsqadmin/package-lock.json
  nsqadmin/static.go
  nsqadmin/static/build/base.css
  nsqadmin/static/build/bootstrap.min.css
  nsqadmin/static/build/favicon.png
  nsqadmin/static/build/glyphicons-halflings-regular.eot
  nsqadmin/static/build/glyphicons-halflings-regular.svg
  nsqadmin/static/build/glyphicons-halflings-regular.ttf
  nsqadmin/static/build/glyphicons-halflings-regular.woff
  nsqadmin/static/build/glyphicons-halflings-regular.woff2
  nsqadmin/static/build/index.html
  nsqadmin/static/build/main.js
  nsqadmin/static/build/main.js.map
  nsqadmin/static/build/nsq_blue.png
  nsqadmin/static/build/vendor.js
  nsqadmin/static/js/lib/handlebars_helpers.js
  nsqadmin/static_debug.go
  nsqadmin/static_legacy.go
Labels: bug, feature

#1365 dist: don't push images
  dist.sh
Labels: bug
