Repository nsqio/nsq, pull requests merged in 2022-08, with the labels that each got.

#1380 nsqd: use metadata struct for both marshal and unmarshal
  nsqd/nsqd.go
  nsqd/nsqd_test.go
Labels: chore

#1376 nsqd: allow unbuffered memory chan if ephemeral or deferred
  nsqd/channel.go
  nsqd/topic.go
Labels: bug

#1415 Update README.md
  README.md
Labels: docs
